import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import style from './styles.module.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Inicio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className={style.main}>
          <nav>
            <h1>My Navbar</h1>
          </nav>
          {children}
        </main>
      </body>
    </html>
  );
}
